### ISSUE TITLE
Suggestion: Bob's Mod Vehicle Equipment for Nuclear Locomotive

### ISSUE THREAD

**Issue by Tosarius** [veden/RampantArsenal#1]
The possibilty to use the equipment would be appreciated.

Could be achieved by changing prototypes\Vehicles.lua line 723 to:
	    categories = {"noInventory","train", "vehicle", "locomotive"}

**Comment by veden** [comment]
That shouldn't be an issue. Does the nuclear tank need something similar?

**Comment by veden** [comment]
Should be a version in the latest, let me know.

**Comment by Tosarius** [comment]
Works perfectly on both, thank you.
