### ISSUE TITLE
Poison and fire artillery doesn't scale

### ISSUE THREAD

**Issue by ghost** [veden/RampantArsenal#14]
basic ammo is stronger than poison and flame after certain point, even though it's an ingredient item for both ammo: https://imgur.com/a/UhWDrAy

Poison at least pretty powerful mid-late game, fire ammo is the most underwhelming. unlike poison which 'infected' biter with disease that  may kill it once it leave the area, Flame Cloud still apply lower dps, I think the duration should be lowered and dps applied higher for Flame Cloud.

The alternative is to make the instant damage higher and lower the cloud dps. at least the instant damage would scale where as the elemental variety is still there.

**Comment by veden** [comment]
So this required changing the cloud mechanic because the damage research doesn't apply to "smoke-with-trigger" entities that are created on ammo.
The updated version is on the mod portal now, let me know if the values work better for you.
