### ISSUE TITLE
Useless repair turrets. Medic turret question/improvement and repair launcher capsules logics

### ISSUE THREAD

**Issue by garrotte13** [veden/RampantArsenal#16]
Medic turret starts repairing cloud for surrounding buildings only when enemy units come nearby. Is it intended?

Repair launcher capsule is thrown by capsule launcher turret at enemy units in range, not at player's harmed entities. Is it to repair vehicles in case they drive to that point a few seconds later?

**Comment by garrotte13** [comment]
Probably both turrets attack enemies - as I see them.
Medic turret has 0 range and creates huge cloud around at whenever enemies are within detection range (28).
Repair capsule launcher ammo is thrown at enemies in hope they are not spitters and have already come up to player's buildings.
That's only my assumption.

**Comment by veden** [comment]
Your assumption is correct.

Yes the medic turret is designed to repair around itself during combat.

Could be, the repair launcher capsule is typically used to be further from the combat and can cover a longer range. Again the turret is triggered by the proximity of enemy units.

This is because it is far more efficient to use enemy triggers than trying to do something with scripts.

**Comment by garrotte13** [comment]
I see. That was very wise if comparing your creation vs Klonan's and others in terms of UPS hunger !!
But it was a huge disappointment for me here: https://www.youtube.com/watch?v=d7DkEbc9xyA

 Now I'm looking for a way in my mod to force any of these turrets to fire when I want it... At least for medic turret.
I need it as an active protection feature vs Warmonger counter strike feature.
Haven't found anything in Factorio API besides creating temp hidden enemy object at the point of counter strike landing :-)

**Comment by garrotte13** [comment]
Pending Feedback?
As I wrote above actual logics of both repairing turrets doesn't help player in most situations at all - they don't shoot, because damage is done by distant attack. It doesn't consume UPS at all - that's great, but both turrets do not heal in general case (attack by spitter or WM counter strike).
I'm planning (after my Rampant3.0 gameplay reaches this point) to research the capabilities of
https://lua-api.factorio.com/latest/LuaEntity.html#LuaEntity.shooting_target
maybe it can help in combination with low UPS consumption by some smart triggers - rare checks or special circumstances checks.

**Comment by garrotte13** [comment]
> https://lua-api.factorio.com/latest/LuaEntity.html#LuaEntity.shooting_target

Despite being RW it doesn't do anything when being set. :-( Hidden enemy object works, but it can lead to chaotic AOE friendly damage :-(

But isn't it UPS-cheap to make some containter entity which looks once per 600 ticks for damaged player buildings in some radius and spends one repair expendable to put healing stickers on all buildings + creates "healing" smoke effect? 600 ticks is just an example. 400 ticks will be fine too. Your healing turrets (like all factorio turrets) shoot not immediately, but after about 100 ticks. With repair capsule launcher it's additional time to throw the capsule -> will be the same 400 ticks.
To make it cheaper some script can register need for healing at some position via on_entity_damaged event. Then such check can be more selectable and take place once per 100 ticks or more often.

>Could be, the repair launcher capsule is typically used to be further from the combat and can cover a longer range. 

It could work fine only in very early game when spitters/worms have small attack range (and it is time when repair turrets are economically not viable for player). But in mid- and end-game enemies' big range attacks plus distance the wall mk2 is built (3 or 4 tiles away from external defense turrets) make both RA repair turrets useless for repairing walls. While construction bots can't be allowed to fly in such dangerous zones. These repair turrets can be used only to heal defense turrets in case of defense breach - where construction bots are almost safe to work too.

**Comment by veden** [comment]
on_entity_damaged can be very expensive in the late-game and something like search every 600 ticks is fine for one or two buildings, but when you get into 30-40 then assume you have an event every 20 ticks at least.

**Comment by garrotte13** [comment]
yep, so far I came to idea that **the only** buildings not repaired by your RA repair turrets are reinforced walls and probably they need another solution, maybe approach from very different point - something like smart bots, not flying when enemies are nearby. Or maybe simple cheating Klonan's mod + fixing addons (there two mods which fix its uber-cheating side effects, need to test them).

While Warmonger counter-strike related damage can be easily repaired by standard construction bots now - no need in RA repair turrets.

**Comment by garrotte13** [comment]
Nothing can be changed in turrets behavior, because they consume 0 UPS and so it should be.

**Comment by garrotte13** [comment]
I added a biter incoming with a Warmonger counter strike. It still is not enough to make Medic turret work. I had to reduce its attackparams warmup to 1 tick.
