### ISSUE TITLE
Suggestion: Specific generator equipment for Nuclear Locomotive

### ISSUE THREAD

**Issue by Tosarius** [veden/RampantArsenal#2]
Since the locomotive is nuclear powered, it would be great to have some kind of generator that simulates tapping into the power grid of the locomotive.

**Comment by veden** [comment]
That shouldn't be an issue. Does the nuclear tank need something similar?

**Comment by veden** [comment]
Should be a version in the latest, let me know.

**Comment by Tosarius** [comment]
Works! Thank you.
