### ISSUE TITLE
Suggestion: min distance for rocket tower and no 360 degree fire radius

### ISSUE THREAD

**Issue by Tosarius** [veden/RampantArsenal#4]
I find it difficult to integrate the rocket towers into my wall of defenses, because of their missing minimum range and their 360 degree fire radius.
Since most of the stronger rockets use an area of effect I'm usually hurting my defenses more than the enemy.

I'd like to suggest a tower that has a slightly longer firing range (we're firing rockets after all) at the "price" of having a minimum firing range and a less than 180 degrees radius. Maybe 90-110 degree?

**Comment by veden** [comment]
An attempt at this should be posted

**Comment by Tosarius** [comment]
I like it, thank you!
