### ISSUE TITLE
Локализация  на русский язык. Исправления и дополнения

### ISSUE THREAD

**Issue by Assisstent** [veden/RampantArsenal#6]
Я исправил перевод на русский язык так, чтобы он выглядел более логично, согласовав в родах и падежах слова между собой, а также исправив глупые ошибки машинного перевода, когда mortar переведено как "строительный раствор". Прошу ознакомиться и добавить в архив

[locale.zip](https://github.com/veden/RampantArsenal/files/6235085/locale.zip)

**Comment by veden** [comment]
is it possible to get this as a pull request?

**Comment by Assisstent** [comment]
"pull request?" I am new at github and don`t know what  it is. If you can`t get it without  "pull request?", I`m afraid I can`t help.

i will try but...

**Comment by veden** [comment]
instead of a zip can you just post the locale.cfg for the RU locale?

**Comment by Astorin** [comment]
I've translated Rampant Arsenal mod to Russian from scratch, see my pull request.

**Comment by veden** [comment]
Thank you
